// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Workout$ReactTemplate = require("./Workout.bs.js");

function renderExerciseSelectList(exercises) {
  return React.createElement("select", {
              className: "form-control mb-2 mr-sm-2"
            }, Belt_List.toArray(List.map((function (e) {
                        return React.createElement("option", {
                                    key: String(e[/* id */0]),
                                    value: String(e[/* id */0])
                                  }, e[/* name */1]);
                      }), exercises)));
}

function renderWorkoutActivities(workoutActivities) {
  return Belt_List.toArray(List.map((function (w) {
                    var tmp;
                    tmp = w.tag ? React.createElement("div", {
                            className: "col-4"
                          }, "Muscle: " + String(w[0])) : React.createElement("div", undefined, "Reps" + String(Workout$ReactTemplate.SetGrouping[/* liftingSetCount */0](w[0])));
                    return React.createElement("li", {
                                className: "list-group-item"
                              }, React.createElement("div", {
                                    className: "container"
                                  }, React.createElement("div", {
                                        className: "row"
                                      }, tmp)));
                  }), workoutActivities));
}

var component = ReasonReact.reducerComponent("WorkoutDetails");

function make(_, _$1, _$2, _$3, _$4) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "container"
                        }, React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "col-md"
                                }, React.createElement("ul", {
                                      className: "list-group mb-2 mr-sm-2 ml-sm-2"
                                    }, React.createElement("li", {
                                          className: "list-group-item"
                                        }))), React.createElement("div", {
                                  className: "col-sm"
                                }), React.createElement("div", {
                                  className: "col-sm"
                                })));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* id */undefined,
                      /* name */"",
                      /* workoutActivities : [] */0,
                      /* reps */10,
                      /* setRest */40,
                      /* selectedExercise */undefined,
                      /* resistance */0.0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, _$1) {
              return /* NoUpdate */0;
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.renderExerciseSelectList = renderExerciseSelectList;
exports.renderWorkoutActivities = renderWorkoutActivities;
exports.component = component;
exports.make = make;
/* component Not a pure module */
